version: '3.9'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db
    command: sleep infinity
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data: